name: Nature7
version: '${version}'
main: io.github.glocation87.nature7.NatureEngine
api-version: '26.2'
description: A minigame engine.

permissions:
  nature7.admin:
    description: Force start sessions and other admin commands.
    default: op
